---
- name: restart vpn-server
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - ipsec
    - xl2tpd
  when: ansible_connection != 'docker'

- name: update sysctl
  command: sysctl -p /etc/sysctl.d/60-vpn-server.conf
  when: ansible_connection != 'docker'
